export const PRICING_PLANS = [
  {
    name: "Starter",
    description: "Personal use, single project",
    price: 79,
    paymentLink: "https://buy.stripe.com/dRm14mfXngO6a7qbZM08g00",
    features: [
      "Full Next.js 16 SaaS boilerplate",
      "NextAuth v5 with Google & GitHub OAuth",
      "Stripe subscriptions, checkout, webhooks",
      "Prisma 6 + PostgreSQL schema",
      "Claude AI integration (auth-gated)",
      "Landing page, pricing page, dashboard",
      "Middleware route protection",
      "Single project license (personal use)",
      "Community support via GitHub Issues",
    ],
  },
  {
    name: "Complete Bundle",
    description: "Best value - all products",
    price: 99,
    paymentLink: "https://buy.stripe.com/5kQeVceTj0P8enGe7U08g06",
    popular: true,
    features: [
      "LaunchFast SaaS Starter (full boilerplate)",
      "SEO Blog Engine (content system)",
      "Indie Hacker Toolkit (launch resources)",
      "PromptVault (64 curated AI prompts)",
      "CursorRules Pro (8 dev configs)",
      "Unlimited projects",
      "Commercial license included",
    ],
  },
  {
    name: "Pro",
    description: "Commercial use, unlimited projects",
    price: 119,
    paymentLink: "https://buy.stripe.com/5kQ4gy26x8hAa7q4xk08g01",
    features: [
      "Everything in Starter",
      "Unlimited projects (commercial license)",
      "Priority email support (24-48h response)",
      "Early access to new features",
      "Pro .cursorrules configs included",
      "Remove 'Built with LaunchFast' attribution",
    ],
  },
] as const;
