export const PRICING_PLANS = [
  {
    name: "Starter",
    description: "Personal use, single project",
    price: 59,
    originalPrice: 79,
    paymentLink: "https://buy.stripe.com/7sYcN4aD3gO60wQ4xk08g07",
    popular: false,
    features: [
      "Full Next.js 16 SaaS boilerplate",
      "NextAuth v5 with Google & GitHub OAuth",
      "Stripe subscriptions, checkout, webhooks",
      "Prisma 6 + PostgreSQL schema",
      "Claude AI integration (auth-gated)",
      "Landing page, pricing page, dashboard",
      "Middleware route protection",
      "Single project license (personal use)",
      "Community support via GitHub Issues",
    ],
  },
  {
    name: "Pro",
    description: "Commercial use, unlimited projects",
    price: 89,
    originalPrice: 119,
    paymentLink: "https://buy.stripe.com/aFabJ07qR41kdjC8NA08g08",
    popular: true,
    features: [
      "Everything in Starter",
      "Unlimited projects (commercial license)",
      "Priority email support (24-48h response)",
      "Early access to new features",
      "Pro AI dev configs included",
      "Remove 'Built with LaunchFast' attribution",
    ],
  },
] as const;
